module.exports = [
  "The Prime Goblins",
  "The Wild Beavers",
  "The Haunting Devils",
  "The Hot Magicians",
  "The Marvelous Asteroids",
  "The Beluga Whales",
  "The Amazing Zombies",
  "The Mysterious Serpents",
  "The Mystery Lemurs",
  "The Clever Wasps",
  "The Spectacular Chargers",
  "The Haunting Miracles",
  "The Classic Wings",
  "The Majestic Toucans",
  "The Happy",
  "The Big Bad Pandas",
  "The White Werewolves",
  "The Exalted Aces",
  "The Prime Goblins",
  "The Flying Swallows",
  "The Courageous Octopi",
  "The Terrific Spiders",
  "The Crunchers",
  "The Wasps",
  "The Lucky Chimpanzees",
  "The Swift Toucans",
  "The Fearless Wizards",
  "The Quick Seals",
  "The Clever Buffalo",
  "The Big Bad Falcons",
  "The Ogres",
  "The Gophers",
  "The Silver Rhinos",
  "The Infernos",
  "The Cubs",
  "The Silver Doves",
  "The Mad Blitzes",
  "The Spirit Blades",
  "The Clever Buffalo",
  "The Silver Jackals",
  "The Exalted Heroes",
  "The Hot Manticores",
  "The Flying Warriors",
  "The Majestic Dinos",
  "The Bright",
  "The Iron Swallows",
  "The Thunder Nightingales",
  "The Skeleton Pelicans",
  "The Golden Ninjas",
  "The Angry Goats",
  "The Proud",
  "The White Scorpions",
  "The Clever",
  "The Marvelous Prowlers",
  "The Fiery Donkeys",
  "The Mystery Lemurs",
  "The Sparrows",
  "The Skeleton Mambas",
  "The Terrific Heroes",
  "The Majestic Dinos",
  "The Warhawks",
  "The Iron Vikings",
  "The Big Cheetahs",
  "The Roadrunners",
  "The Fabulous Orcs",
  "The Wise Buccaneers",
  "The Amazing Robins",
  "The Magic Rockets",
  "The Prime Serpents",
  "The Fantastic Barracudas",
  "The Free",
  "The True Llamas",
  "The Skeleton Enigmas",
  "The Big Bad Roadrunners",
  "The Bitter Donkeys",
  "The Infernos",
  "The Great Sailors",
  "The Great Predators",
  "The Flawless Chimpanzees",
  "The Wizards",
  "The Calm Blitzes",
  "The Proud Horses",
  "The Iron",
  "The Glorious Dolphins",
  "The Majestic Chimpanzees",
  "The Titans",
  "The Grand Androids",
  "The Predators",
  "The Spirit Gators",
  "The Proud Orcs",
  "The Terrific Rovers",
  "The Crazy Pandas",
  "The Black Crocs",
  "The Brute Androids",
  "The Bitter Sparrows",
  "The Storm Tigers",
  "The Monstrous Bees",
  "The Defiant",
  "The Majestic Dinos",
  "The Storm Gorillas",
  "The Thunder Ogres",
  "The Thunder Orcas",
];
